### ISSUE TITLE
Questions regarding the code, paper

### ISSUE THREAD

**Issue by just1nseo** [AmourWaltz/UAlign#1]
Hi, I have read your paper, UAlign, and was interested in the idea so wanted to check out the implementation. 

First of all, thank you for the great work!

What I was confused about while reading the paper was, if I understood properly, the reward model is trained to give a binary classification of whether the output of the policy model is true based on the prompt, the output itself, and two different uncertainty estimations. 

So if that is the case, what exactly is the policy model given as a reward while performing PPO? I wanted to clarify that understanding through code implementation, but I believe the codes related to PPO training are missing. 

I would deeply appreciate it if you could release the refactored version of the code, and give me some additional explanation regarding the PPO training detail. It would definitely help me clear some misunderstandings about your paper.  

Thank you again for your great work! Looking forward to your reply :)

**Comment by AmourWaltz** [comment]
@just1nseo Thanks for your interest in our work. As the paper was just released, I'm still managing the project and code, and will update in two weeks.

**Comment by just1nseo** [comment]
@AmourWaltz Thank you for such a quick response! Will look forward to your update.
